import {describe, expect, it} from 'vitest';
import request from 'supertest';
import {createApp} from '../src/server/index';
import {diffRevisions, expand, resolveWallTime, type RuleDoc} from '../src/server/recurrence';

const base = (overrides: Partial<RuleDoc>): RuleDoc => ({
  timezone: 'America/New_York',
  dstPolicy: 'earlier',
  segments: [],
  exceptions: [],
  ...overrides,
});

const daily = (id: string, interval: number, time = '09:00', start = '2026-01-01', extra: Record<string, unknown> = {}) => ({
  id, frequency: 'DAILY' as const, interval, localTime: time, start, ...extra,
});

describe('DST wall time resolution', () => {
  it('resolves spring-forward gaps according to policy', () => {
    // 2026-03-08 02:30 does not exist in America/New_York.
    const earlier = resolveWallTime('America/New_York', '2026-03-08', '02:30', 'earlier');
    const later = resolveWallTime('America/New_York', '2026-03-08', '02:30', 'later');
    expect(earlier.resolution).toBe('gap-earlier');
    expect(later.resolution).toBe('gap-later');
    expect(later.instant - earlier.instant).toBe(3_600_000);
  });

  it('resolves fall-back overlaps according to policy', () => {
    // 2026-11-01 01:30 happens twice in America/New_York.
    const earlier = resolveWallTime('America/New_York', '2026-11-01', '01:30', 'earlier');
    const later = resolveWallTime('America/New_York', '2026-11-01', '01:30', 'later');
    expect(earlier.resolution).toBe('overlap-earlier');
    expect(later.resolution).toBe('overlap-later');
    expect(later.instant - earlier.instant).toBe(3_600_000);
    expect(earlier.utcOffsetMinutes).toBe(-240);
    expect(later.utcOffsetMinutes).toBe(-300);
  });
});

describe('revision diff scenarios', () => {
  it('timezone-only change: same keys, every occurrence is a time change (no adds/removes)', () => {
    const oldDoc = base({segments: [daily('s', 1)]});
    const newDoc = base({timezone: 'America/Chicago', segments: [daily('s', 1)]});
    const result = diffRevisions(
      expand(oldDoc, '2026-01-01', '2026-03-31'),
      expand(newDoc, '2026-01-01', '2026-03-31'),
      '2026-01-01', '2026-03-31',
    );
    expect(result.stats.added + result.stats.removed).toBe(0);
    expect(result.stats.modified).toBe(result.stats.total);
    // Instants shift by exactly one hour (NY -> Chicago) in January.
    const item = result.items.find(i => i.next?.localDate === '2026-01-15')!;
    const delta = Date.parse(item.next!.instant) - Date.parse(item.old!.instant);
    expect(delta).toBe(3_600_000);
    expect(item.old!.key).toBe(item.next!.key);
  });

  it('interval change: unmatched ordinals become delete + add, never guessed matches', () => {
    const oldDoc = base({segments: [daily('s', 1)]});
    const newDoc = base({segments: [daily('s', 2)]});
    const result = diffRevisions(
      expand(oldDoc, '2026-01-01', '2026-01-10'),
      expand(newDoc, '2026-01-01', '2026-01-10'),
      '2026-01-01', '2026-01-10',
    );
    // Keys differ by fingerprint/ordinal, so even shared dates do not pair up.
    expect(result.stats.modified).toBe(0);
    expect(result.stats.removed).toBe(10);
    expect(result.stats.added).toBe(5);
    // Interval-2 DAILY is anchored to the 1970 epoch: even ordinal days
    // (2026-01-01, 03, 05...) generate; Jan 4 is not generated by either shape.
    const jan3Old = result.items.find(i => i.old?.localDate === '2026-01-03');
    expect(jan3Old?.type).toBe('removed');
    expect(jan3Old?.key).toMatch(/^occ\|DAILY1\/p0@09:00\|20456$/);
    const jan5New = result.items.find(i => i.next?.localDate === '2026-01-05');
    expect(jan5New?.type).toBe('added');
    expect(jan5New?.key).toMatch(/^occ\|DAILY2\/p0@09:00\|10229$/);
    expect(result.items.every(i => !(i.type === 'added' && i.next?.localDate === '2026-01-04'))).toBe(true);
  });

  it('rule segmentation with unchanged shape preserves keys across the split', () => {
    const oldDoc = base({segments: [daily('all', 1, '09:00', '2026-01-01')]});
    const newDoc = base({
      segments: [
        daily('h1', 1, '09:00', '2026-01-01', {until: '2026-02-15'}),
        daily('h2', 1, '09:00', '2026-02-16', {until: '2026-03-31'}),
      ],
    });
    const result = diffRevisions(
      expand(oldDoc, '2026-01-01', '2026-03-31'),
      expand(newDoc, '2026-01-01', '2026-03-31'),
      '2026-01-01', '2026-03-31',
    );
    expect(result.stats.added + result.stats.removed + result.stats.modified).toBe(0);
    expect(result.stats.same).toBe(90);
    // Provenance follows the new segment boundary.
    const afterSplit = result.items.find(i => i.next?.localDate === '2026-03-01')!;
    expect(afterSplit.next!.source).toEqual({kind: 'segment', id: 'h2'});
  });

  it('two independent same-shape segments at different wall times never collide', () => {
    // standup 09:00 and nightly 21:00 share shape DAILY/1 but are separate lines.
    const one = base({segments: [daily('standup', 1, '09:00')]});
    const two = base({segments: [daily('standup', 1, '09:00'), daily('nightly', 1, '21:00')]});
    const result = diffRevisions(
      expand(one, '2026-01-01', '2026-01-07'),
      expand(two, '2026-01-01', '2026-01-07'),
      '2026-01-01', '2026-01-07',
    );
    expect(result.stats.added).toBe(7);
    expect(result.stats.removed).toBe(0);
    expect(result.stats.modified).toBe(0);
    expect(result.stats.same).toBe(7);
    // Editing only standup's wall time pairs on the same key and leaves nightly alone.
    const moved = base({segments: [daily('standup', 1, '10:00'), daily('nightly', 1, '21:00')]});
    const movedResult = diffRevisions(
      expand(two, '2026-01-01', '2026-01-07'),
      expand(moved, '2026-01-01', '2026-01-07'),
      '2026-01-01', '2026-01-07',
    );
    expect(movedResult.stats.modified).toBe(7);
    expect(movedResult.stats.same).toBe(7);
    expect(movedResult.stats.added + movedResult.stats.removed).toBe(0);
  });

  it('frequency change across a split is still delete + add (no guessing)', () => {
    const oldDoc = base({segments: [daily('all', 1, '09:00', '2026-01-01')]});
    const newDoc = base({
      segments: [{id: 'w', frequency: 'WEEKLY', interval: 1, localTime: '09:00', start: '2026-01-05', byWeekDay: ['MO']}],
    });
    const result = diffRevisions(
      expand(oldDoc, '2026-01-01', '2026-03-31'),
      expand(newDoc, '2026-01-01', '2026-03-31'),
      '2026-01-01', '2026-03-31',
    );
    expect(result.stats.modified).toBe(0);
    expect(result.stats.added).toBeGreaterThan(0);
    expect(result.stats.removed).toBeGreaterThan(0);
  });

  it('exception replacement: locatable on both sides when target survives, orphaned when cadence changes', () => {
    const oldDoc = base({
      segments: [daily('s', 1)],
      exceptions: [{
        id: 'move', kind: 'replace' as const, segmentId: 's', date: '2026-01-20',
        replacement: {localDate: '2026-01-21', localTime: '11:00'},
      }],
    });
    const newDocSameShape = base({
      segments: [daily('s', 1)],
      exceptions: [{
        id: 'move', kind: 'replace' as const, segmentId: 's', date: '2026-01-20',
        replacement: {localDate: '2026-01-22', localTime: '10:30'},
      }],
    });
    const sameShape = diffRevisions(
      expand(oldDoc, '2026-01-01', '2026-02-28'),
      expand(newDocSameShape, '2026-01-01', '2026-02-28'),
      '2026-01-01', '2026-02-28',
    );
    const row = sameShape.exceptions.find(e => e.id === 'move')!;
    expect(row.status).toBe('retargeted');
    expect(row.old?.resolved).toBe(true);
    expect(row.next?.resolved).toBe(true);
    // The replacement occurrence keeps the same stable exception key, so moving
    // it to another day/time surfaces as a time change (not delete + add).
    const replaceItems = sameShape.items.filter(i => i.key === 'occ|exc:replace:move');
    expect(replaceItems).toHaveLength(1);
    expect(replaceItems[0].type).toBe('modified');
    expect(replaceItems[0].old!.localDate).toBe('2026-01-21');
    expect(replaceItems[0].next!.localDate).toBe('2026-01-22');

    // With interval 2 starting at epoch, 2026-01-20 is no longer generated.
    const newDocCadence = base({
      segments: [daily('s', 2)],
      exceptions: [{
        id: 'move', kind: 'replace' as const, segmentId: 's', date: '2026-01-20',
        replacement: {localDate: '2026-01-21', localTime: '11:00'},
      }],
    });
    const orphaned = diffRevisions(
      expand(oldDoc, '2026-01-01', '2026-02-28'),
      expand(newDocCadence, '2026-01-01', '2026-02-28'),
      '2026-01-01', '2026-02-28',
    );
    const orphanRow = orphaned.exceptions.find(e => e.id === 'move')!;
    expect(orphanRow.status).toBe('orphaned');
    expect(orphanRow.next?.resolved).toBe(false);
    expect(orphanRow.next?.reason).toMatch(/no occurrence/);
  });

  it('exceptions stay locatable after a same-shape segment is split and renamed', () => {
    const oldDoc = base({
      segments: [daily('standup', 1)],
      exceptions: [
        {id: 'cancel-day', kind: 'cancel' as const, segmentId: 'standup', date: '2026-02-09'},
        {id: 'big', kind: 'cancelRange' as const, segmentId: 'standup', date: '2026-02-01', endDate: '2026-02-28'},
      ],
    });
    const newDoc = base({
      segments: [
        daily('standup-h1', 1, '09:00', '2026-01-01', {until: '2026-06-30'}),
        daily('standup-h2', 1, '09:00', '2026-07-01'),
      ],
      exceptions: [
        {id: 'cancel-day', kind: 'cancel' as const, segmentId: 'standup-h1', date: '2026-02-09'},
        // Old id 'standup' no longer exists; retarget onto any generating line.
        {id: 'big', kind: 'cancelRange' as const, segmentId: 'standup', date: '2026-02-01', endDate: '2026-02-28'},
      ],
    });
    const result = diffRevisions(
      expand(oldDoc, '2026-02-01', '2026-02-28'),
      expand(newDoc, '2026-02-01', '2026-02-28'),
      '2026-02-01', '2026-02-28',
    );
    for (const id of ['cancel-day', 'big']) {
      const row = result.exceptions.find(e => e.id === id)!;
      expect(row.next?.resolved, `${id} should resolve after split`).toBe(true);
      expect(row.status).not.toBe('orphaned');
    }
  });

  it('dst policy flip surfaces the shifted occurrence and records resolution', () => {
    const oldDoc = base({dstPolicy: 'earlier', segments: [daily('s', 1, '02:30')]});
    const newDoc = base({dstPolicy: 'later', segments: [daily('s', 1, '02:30')]});
    const result = diffRevisions(
      expand(oldDoc, '2026-03-01', '2026-03-15'),
      expand(newDoc, '2026-03-01', '2026-03-15'),
      '2026-03-01', '2026-03-15',
    );
    const gap = result.items.find(i => i.old?.localDate === '2026-03-08')!;
    expect(gap.type).toBe('modified');
    expect(gap.old!.dstResolution).toBe('gap-earlier');
    expect(gap.next!.dstResolution).toBe('gap-later');
    // All non-gap days remain unchanged.
    const changedDates = result.items.filter(i => i.type === 'modified').map(i => i.old!.localDate);
    expect(changedDates).toEqual(['2026-03-08']);
  });

  it('large window cancelRange removes a broad span and reports unresolved when empty', () => {
    const oldDoc = base({segments: [daily('s', 1)]});
    const newDoc = base({
      segments: [daily('s', 1)],
      exceptions: [{id: 'big-cancel', kind: 'cancelRange', segmentId: 's', date: '2026-02-01', endDate: '2026-12-31'}],
    });
    const result = diffRevisions(
      expand(oldDoc, '2026-01-01', '2026-03-31'),
      expand(newDoc, '2026-01-01', '2026-03-31'),
      '2026-01-01', '2026-03-31',
    );
    // January remains; everything in February and March is removed via the range.
    expect(result.stats.removed).toBe(59);
    expect(result.items.filter(i => i.type === 'same')).toHaveLength(31);
    const row = result.exceptions.find(e => e.id === 'big-cancel')!;
    expect(row.next?.resolved).toBe(true);

    // A range that no longer overlaps anything (different cadence window) is unresolved.
    const emptyDoc = base({
      segments: [daily('s', 1, '09:00', '2027-01-01')],
      exceptions: [{id: 'ghost', kind: 'cancelRange', segmentId: 's', date: '2026-02-01', endDate: '2026-03-01'}],
    });
    const expansion = expand(emptyDoc, '2026-01-01', '2026-06-30');
    expect(expansion.resolutions.get('ghost')!.resolved).toBe(false);
  });
});

describe('ordering stability', () => {
  it('produces identical key order across repeated diffs', () => {
    const oldDoc = base({segments: [daily('s', 1)]});
    const newDoc = base({timezone: 'Asia/Tokyo', segments: [daily('s', 1)]});
    const run = () => diffRevisions(
      expand(oldDoc, '2026-01-01', '2026-02-28'),
      expand(newDoc, '2026-01-01', '2026-02-28'),
      '2026-01-01', '2026-02-28',
    ).items.map(i => i.key);
    const first = run();
    expect(run()).toEqual(first);
    expect([...first]).toEqual([...first].sort()); // keys coincide with instant order
  });
});

// ---------------------------------------------------------------------------
// HTTP / streaming tests
// ---------------------------------------------------------------------------

interface StreamResult {
  events: {id: number; event: string; data: any}[];
  done: Promise<void>;
}

function openStream(app: ReturnType<typeof createApp>, url: string, lastEventId?: number): StreamResult {
  const events: StreamResult['events'] = [];
  const req = request(app).get(url).buffer(true).parse((res, cb) => {
    let buffer = '';
    res.on('data', chunk => {
      buffer += chunk.toString();
      let sep: number;
      while ((sep = buffer.indexOf('\n\n')) >= 0) {
        const raw = buffer.slice(0, sep);
        buffer = buffer.slice(sep + 2);
        let id = 0;
        let event = 'message';
        const dataLines: string[] = [];
        for (const line of raw.split('\n')) {
          if (line.startsWith('id:')) id = Number(line.slice(3).trim());
          else if (line.startsWith('event:')) event = line.slice(6).trim();
          else if (line.startsWith('data:')) dataLines.push(line.slice(5).trim());
        }
        if (event === 'ping' || raw.startsWith(':')) continue;
        events.push({id, event, data: JSON.parse(dataLines.join(''))});
      }
    });
    res.on('end', () => cb(null, Buffer.alloc(0)));
    res.on('error', cb);
  });
  if (lastEventId !== undefined) req.set('Last-Event-ID', String(lastEventId));
  const done = req.then(() => undefined);
  return {events, done};
}

describe('compare HTTP API', () => {
  it('pins both revisions in a session and streams complete ordered results', async () => {
    const app = createApp();
    const created = await request(app).post('/api/schedules/alpha/compare')
      .send({oldRevision: 1, newRevision: 2, from: '2026-01-01', to: '2026-01-31'})
      .expect(201);
    expect(created.body.oldRevision).toBe(1);
    expect(created.body.newRevision).toBe(2);

    const stream = openStream(app, created.body.streamUrl);
    await stream.done;

    const names = stream.events.map(e => e.event);
    expect(names[0]).toBe('start');
    expect(names[names.length - 1]).toBe('done');
    expect(stream.events.filter(e => e.event === 'item').length).toBeGreaterThan(0);

    const done = stream.events.find(e => e.event === 'done')!.data;
    expect(done.complete).toBe(true);
    expect(done.stats.added + done.stats.removed).toBe(0);
    expect(done.stats.modified).toBeGreaterThan(0);

    // Event ids are sequential and item keys are in stable order.
    const ids = stream.events.map(e => e.id);
    expect(ids).toEqual(ids.map((_, i) => i + 1));
    const instants = stream.events.filter(e => e.event === 'item').map(e =>
      e.data.old?.instant ?? e.data.next.instant);
    expect(instants).toEqual([...instants].sort());

    // Seeded orphan: r3 stand-up interval 2, cancel targets 2026-02-09.
    const orphanSession = await request(app).post('/api/schedules/alpha/compare')
      .send({oldRevision: 1, newRevision: 3, from: '2026-02-01', to: '2026-02-28'})
      .expect(201);
    const orphanStream = openStream(app, orphanSession.body.streamUrl);
    await orphanStream.done;
    const ex = orphanStream.events.find(e => e.event === 'exception' && e.data.id === 'cancel-holiday')!.data;
    expect(ex.status).toBe('orphaned');
    expect(ex.next.resolved).toBe(false);
  });

  it('resumes with Last-Event-ID and replays only missed events', async () => {
    const app = createApp();
    const created = await request(app).post('/api/schedules/alpha/compare')
      .send({oldRevision: 1, newRevision: 2, from: '2026-01-01', to: '2026-01-15'})
      .expect(201);
    const first = openStream(app, created.body.streamUrl);
    await first.done;
    const resumeAfter = first.events[2].id;
    const resumed = openStream(app, created.body.streamUrl, resumeAfter);
    await resumed.done;
    expect(resumed.events.length).toBe(first.events.length - resumeAfter);
    expect(resumed.events[0].id).toBe(resumeAfter + 1);
  });

  it('rejects unknown revisions and invalid windows', async () => {
    const app = createApp();
    await request(app).post('/api/schedules/alpha/compare')
      .send({oldRevision: 1, newRevision: 99, from: '2026-01-01', to: '2026-01-31'})
      .expect(400);
    await request(app).post('/api/schedules/alpha/compare')
      .send({oldRevision: 2, newRevision: 1, from: '2026-03-01', to: '2026-01-01'})
      .expect(400);
    await request(app).get('/api/compare/nope/stream').expect(404);
  });

  it('does not let later saves mutate a pinned session', async () => {
    const app = createApp();
    const head = await request(app).get('/api/schedules/alpha').expect(200);
    // Pin r2 (Chicago) -> r4 (NY segmented); wall-clock times identical.
    const created = await request(app).post('/api/schedules/alpha/compare')
      .send({oldRevision: 2, newRevision: head.body.revision, from: '2026-01-01', to: '2026-01-10'})
      .expect(201);
    const doc = JSON.parse(head.body.content);
    doc.segments[0].localTime = '04:00';
    await request(app).put('/api/schedules/alpha')
      .send({doc, revision: head.body.revision, note: 'later edit'})
      .expect(200);
    const stream = openStream(app, created.body.streamUrl);
    await stream.done;
    const done = stream.events.find(e => e.event === 'done')!.data;
    expect(done.complete).toBe(true);
    // Session is pinned to the saved r4, which never contains 04:00.
    const items = stream.events.filter(e => e.event === 'item');
    for (const e of items) {
      if (e.data.next) expect(e.data.next.localTime).not.toBe('04:00');
    }
  });
});
